### ISSUE TITLE
findOne return Null Page in ready.php

### ISSUE THREAD

**Issue by germankirichenko** [adrianbj/RestrictTabView#3]
Hi, Adrian!

When you search any Page through findOne from the ready.php file and if the module says that the View Tab needs to be hidden, the search returns NullPage.

I think it happened after Ryan updated the findOne method (commit [6758fb5](https://github.com/processwire/processwire/commit/6758fb525e27ab0e151d314904e2f0fed27085e1)).

The get, findOne with include=all and find->first() methods return a page.

I disabled hook Page::viewable and search returns page. But the dropdown for the View tab is displayed on the edit page.

**Comment by adrianbj** [comment]
Thank for the report @germankirichenko - I can't reproduce for some reason, but at the same time I am not really sure why I took that approach of actually making the page not viewable - this module is about hiding tabs, not controlling permissions, so I don't think it really should be preventing view access.

Can you please try replacing the `removeTabs()` method with this and let me know if it's working as expected.
```
    private function removeTabs ($tab, $event) {

        $form = $event->return;

        if($tab == "Settings") {
            if(!$this->data['showNameInContentTab']) {
                $pn = $form->getChildByName('_pw_page_name');
                if ($pn instanceof Inputfield) {
                    $pn->wrapAttr('style', 'display:none;');
                }
            }
        }

        if($tab == "Settings" || $tab == "Children" || $tab == "Restore" || $tab == "Delete") {
            $fieldset = $form->find("id=ProcessPageEdit".$tab)->first();
        }
        else {
            $fieldset = $form->find("id=ProcessPageEdit".$tab);
        }
        if(!is_object($fieldset)) return;

        $form->remove($fieldset);
        $event->object->removeTab("ProcessPageEdit".$tab);
    }
```

**Comment by germankirichenko** [comment]
@adrianbj, I know why you chose this approach) Because the View tab is generated if $ page->viewable in the ProcessPageEdit module. It generates a drop-down list with buttons. And if you hide the View tab, then dropdown remains at the bottom of the page))

**Comment by germankirichenko** [comment]
@adrianbj, I rewrote your module and added permissions page-tabs-view, page-tabs-settings, page-tabs-children e.t.c .. The module adds them when troubleshooting, and checks if the role has access to view the tab. This way I can add permission to view each tab to the role. And I can redefine it at the template level.

**Comment by germankirichenko** [comment]
@adrianbj, like this:

`protected function beforeBuildFormContent(HookEvent $event) {

    $page = $event->object->getPage();
    $template = $page->template;
    $user = $this->wire('user');

    $settings = in_array("Settings", $this->data['systemTabs']);
    $permission = "page-tabs-settings";
    $access = $user->hasTemplatePermission($permission, $template);

    if ($settings && !$access && !$template->nameContentTab) {
      $template->nameContentTab = 1;
    }

  }



  protected function afterBuildForm(HookEvent $event) {

    $page = $event->object->getPage();
    $template = $page->template;
    $user = $this->wire('user');

    foreach ($this->data['systemTabs'] as $tab) {
      $permission = "page-tabs-" . strtolower($tab);
      $access = $user->hasTemplatePermission($permission, $template);

      if (!$access) $this->hideTabContent($tab, $event);

    }

  }



  private function hideTabContent($tab, $event) {

    $page = $event->object->getPage();
    $form = $event->return;
		$wrappers = $form->children();

    if ($tab == "Settings" && !$this->data['showNameInContentTab']) {
      $field = $form->getChildByName('_pw_page_name');
      if ($field instanceof Inputfield) $field->wrapAttr('style', 'display:none;');
    }

    if ($tab == 'View') {
      $this->addHookAfter('Page::viewable', function(HookEvent $event) {
        $event->return = false;
      });
    }

    $fid = 'ProcessPageEdit' . $tab;
    $wrapper = $wrappers->get("id={$fid}");
    if ($wrapper) $wrappers->remove($wrapper);

    $event->object->removeTab($fid);

  }`

**Comment by germankirichenko** [comment]
@adrianbj, I cannot find a solution on how to hide the view tab correctly.

**Comment by germankirichenko** [comment]
@adrianbj, You can reproduce this by creating in Ready.php a hook for after Pages::saveReady, in it try to find some page where the view tab is hidden. Check findOne, get, and find. 

The solution you wrote finds the page, hides the tab, but the drop-down list that appeared when you hover over the view tab is located at the bottom of the page outside the form.

**Comment by adrianbj** [comment]
Yeah, I can see the issue with that dropdown appearing at the bottom of the page. I am trying to figure out how to get rid of it. I thought maybe hooking into `ProcessPageEdit::buildFormView` would work, but I can't seem to adjust the output. I am wonder if a JS solution might be the only option.

I don't really have much time for this at the moment - do you feel like investigating to see if that hook will work, or if JS is the better approach?

**Comment by germankirichenko** [comment]
@adrianbj 
I will test this option and notify you.

**Comment by germankirichenko** [comment]
@adrianbj, with the hook `ProcessPageEdit::buildFormView` nothing happened, because it generates the View button itself, and dropdown has already been added to $out.

I did it this way, can you tell me how to simplify it?

```
static public function getDefaultData() {
    return array(
        "viewTabs" => array(),
        "hideTabs" => array(),
        "specifiedTemplates" => array(),
        "showNameInContentTab" => false,
        "hideViewDropdown" => false
    );
}



public function init() {
    if($this->wire('user')->isSuperuser()) return;
    $this->addHookBefore('ProcessPageEdit::buildFormContent', $this, "beforeBuildFormContent");
    $this->addHookAfter('ProcessPageEdit::buildForm', $this, "afterBuildForm");
    $this->addHookAfter('ProcessPageEdit::execute', $this, "hideViewDropdown");
}



private function removeTabs ($tab, $event) {
    
    $form = $event->return;
    
    if($tab == "Settings") {
        if(!$this->data['showNameInContentTab']) {
            $pn = $form->getChildByName('_pw_page_name');
            if ($pn instanceof Inputfield) $pn->wrapAttr('style', 'display:none;');
        }
    }
    
    if($tab == "View") {
        $fieldset = $form->find("id=ProcessPageEdit".$tab);
        $this['hideViewDropdown'] = true;
    }
    else {
        $fieldset = $form->find("id=ProcessPageEdit".$tab)->first();
    }
    if(!is_object($fieldset)) return;
    $form->remove($fieldset);
    $event->object->removeTab("ProcessPageEdit".$tab);

}



protected function hideViewDropdown (HookEvent $event) {

    if ($this['hideViewDropdown']) {
        $script = implode('', array(
            '<script>',
                '$(document).ready(function() {',
                    '$("#_ProcessPageEditViewDropdown").remove()',
                '});',
            '</script>'
        ));
        $event->return .= $script;
    }

}
```

**Comment by adrianbj** [comment]
Thanks for your work on this - it does look like JS is going to be the only viable solution.

I reworked a little so as to avoid a separate permission - I don't think there is any need for that - if someone wants the View tab hidden, then the dropdown should be hidden automatically.

Please try this version - sorry about the txt extension - it wouldn't let me upload a .module file.
[RestrictTabView.txt](https://github.com/adrianbj/RestrictTabView/files/4709298/RestrictTabView.txt)

**Comment by germankirichenko** [comment]
Where View is added to the $ hiddenTabs array?

**Comment by adrianbj** [comment]
If I understand you question correctly, it is taken care of in the new `getHiddenTabs()` method.

**Comment by germankirichenko** [comment]
))) Sorry, I just woke up))) Excellent!

**Comment by adrianbj** [comment]
I have committed the new version, but also added the removal of the "Save & View" option in the Save dropdown.

Let me know if you find any problems.

**Comment by germankirichenko** [comment]
Ok)

**Comment by germankirichenko** [comment]
@adrianbj 
I think that the Save & View button should not be hidden because it does not apply to tabs

**Comment by adrianbj** [comment]
Fair enough - I have remove that in the latest version.
